CREATE DATABASE IF NOT EXISTS fruitdb DEFAULT CHARACTER SET utf8mb4;

USE fruitdb;

CREATE TABLE IF NOT EXISTS owner(
	username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL
);

INSERT INTO owner (username, password) VALUES ('admin', 'admin123')
ON DUPLICATE KEY UPDATE password=VALUES(password);

CREATE TABLE IF NOT EXISTS products(
	code INT PRIMARY KEY UNIQUE NOT NULL,
	name VARCHAR(100) UNIQUE NOT NULL,
    price INT NOT NULL,
    amount INT NOT NULL
);

