CREATE DATABASE IF NOT EXISTS fruitdb DEFAULT CHARACTER SET utf8mb4;

USE fruitdb;

CREATE TABLE IF NOT EXISTS products(
	code INT PRIMARY KEY UNIQUE NOT NULL,
	name VARCHAR(100) UNIQUE NOT NULL,
    price INT NOT NULL,
    amount INT NOT NULL
);

